### ISSUE TITLE
docs: add description to endpoints

### ISSUE THREAD

**Issue by tokitouq** [tokitouq/mangareader-api#195]
Helpful links:

https://fastapi.tiangolo.com/tutorial/metadata/#create-metadata-for-tags
https://fastapi.tiangolo.com/tutorial/metadata/#use-your-tags
https://fastapi.tiangolo.com/tutorial/path-operation-configuration/#description-from-docstring
https://fastapi.tiangolo.com/tutorial/path-operation-configuration/#summary-and-description

**Comment by mariyam-siddiqui** [comment]
Is there an existing documentation to add the changes? the links in the readme are not responsive.

**Comment by tokitouq** [comment]
hi @mariyam-siddiqui, appreciate your interest in this project.
There are some essential patches left for endpoint routing.

> the links in the readme are not responsive.

Api versioning needs a little bit of work

I will update you after fixing these things  ( will try to fix it today ).

**Comment by tokitouq** [comment]
@mariyam-siddiqui 
Sorry I fixed this myself since I didnt get any response from you.
related PR: https://github.com/tokitouq/mangareader-api/pull/297

Closing this...
